
name-template: 'v$RESOLVED_VERSION 🌟'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 新功能'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 修復錯誤'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧹 優化/重構'
    labels:
      - 'refactor'
      - 'chore'
  - title: '📚 文件變更'
    labels:
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

# 版本遞增的規則
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

# 版本的標籤規則
version-template: '$MAJOR.$MINOR'
prerelease: true
prerelease-identifier: 'beta'

# 變更日誌的範本
template: |
  ## 🚀 版本內容

  $CHANGES

  **感謝貢獻者** 🎉：
  $CONTRIBUTORS
